version: '3.4'
services:
 #Jenkins Master
 master:
  build: jenkins-master/.
  volumes:
   - jenkinslog:/var/log/jenkins
   - jenkinshome:/var/jenkins_home
  ports:
   - "50000:50000"
  restart: unless-stopped
 #Main NGINX Instance - Ingress point
 nginx:
  build: jenkins-nginx/.
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - /etc/letsencrypt:/etc/letsencrypt
  restart: unless-stopped
 
 slave:
  build: jenkins-slave
 
 slavedotnet:
  build: jenkins-dotnetcore-slave

volumes:
  jenkinslog:
  jenkinshome:

