data:
 build: jenkins-data
master:
 build: jenkins-master
 volumes_from:
  - data
 ports:
  - "50000:50000"
nginx:
 build: jenkins-nginx
 ports:
  - "80:80"
  - "5000:443"
 links:
  - master:jenkins-master
slave:
 build: jenkins-slave
slavedotnet:
 build: jenkins-dotnetcore-slave
