version: '3.4'
services:
 master:
  build: jenkins-master/.
  volumes:
   - jenkinslog:/var/log/jenkins
   - jenkinshome:/var/jenkins_home
  ports:
   - "50000:50000"
  networks:
   - jenkins-net
 nginx:
  build: jenkins-nginx/.
  ports:
   - "80:80"
   - "443:443"
   networks:
    - jenkins-net
  volumes:
   - /etc/letsencrypt:/etc/letsencrypt
 slave:
  build: jenkins-slave
 slavedotnet:
  build: jenkins-dotnetcore-slave
volumes:
  jenkinslog:
  jenkinshome:
networks:
 jenkins-net:




